PullRequest:
  opened: |
    Hello @$AUTHOR :wave: 

    I'm your friendly neighborhood bot and would like to say thank you for
    submitting a pull request to Hyperion!

    To help you and other users test your changes faster,
    see [GitHub Actions](https://github.com/$REPO_FULL_NAME/actions/runs/@$RUN_ID) for finished workflow artifacts.

    If you make changes to your PR, i create a new link to your workflow
    artifacts for each commit.

    Best regards,
    Hyperion-Project
  synchronize: |
    I have a new link to your workflow artifacts for you:
    [GitHub Actions](https://github.com/$REPO_FULL_NAME/actions/runs/@$RUN_ID)
      
