set(USE_SYSTEM_QMDNS_LIBS ${DEFAULT_USE_SYSTEM_QMDNS_LIBS} CACHE BOOL "use qmdnsengine library from system")

if(USE_SYSTEM_QMDNS_LIBS)
	find_package(qmdnsengine REQUIRED)
else()
	set(QMDNS_CMAKE_ARGS
		-DBUILD_SHARED_LIBS:BOOL=OFF
		-DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_BINARY_DIR}
		-DBIN_INSTALL_DIR:STRING=lib
		-DLIB_INSTALL_DIR:STRING=lib
		-DINCLUDE_INSTALL_DIR:STRING=include
		-DCMAKE_PREFIX_PATH:PATH=${CMAKE_PREFIX_PATH}
		-DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
		-DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
		-DCMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
		-DCMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS}
		-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
		-Wno-dev # We don't want to be warned over unused variables
	)

	if(CMAKE_CROSSCOMPILING)
		string(REPLACE ";" "$<SEMICOLON>" CMAKE_OSX_ARCHITECTURES_ "${CMAKE_OSX_ARCHITECTURES}")
		list(APPEND QMDNS_CMAKE_ARGS
			-DCMAKE_OSX_ARCHITECTURES:STRING=${CMAKE_OSX_ARCHITECTURES_}
			-DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=${CMAKE_OSX_DEPLOYMENT_TARGET}
		)
	endif()

	include(ExternalProject)
	ExternalProject_Add(qmdns
		PREFIX				${CMAKE_CURRENT_BINARY_DIR}/external/qmdnsengine
		BUILD_ALWAYS		OFF
		DOWNLOAD_COMMAND	""
		BINARY_DIR			${CMAKE_CURRENT_BINARY_DIR}/external/qmdnsengine/bin
		SOURCE_DIR			${CMAKE_SOURCE_DIR}/dependencies/external/qmdnsengine
		CMAKE_ARGS			${QMDNS_CMAKE_ARGS}
		INSTALL_DIR			${CMAKE_BINARY_DIR}
		BUILD_BYPRODUCTS    <INSTALL_DIR>/lib/${CMAKE_STATIC_LIBRARY_PREFIX}qmdnsengine${CMAKE_STATIC_LIBRARY_SUFFIX}
	)

	add_library(qmdnsengine STATIC IMPORTED GLOBAL)
	add_dependencies(qmdnsengine qmdns)
	ExternalProject_Get_Property(qmdns INSTALL_DIR)
	set_target_properties(qmdnsengine PROPERTIES
		IMPORTED_LOCATION "${INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}qmdnsengine${CMAKE_STATIC_LIBRARY_SUFFIX}"
		INTERFACE_INCLUDE_DIRECTORIES "${INSTALL_DIR}/include"
	)
endif()
