name: GitHub Actions
on:
  pull_request:
    branches:
      - master

jobs:
  comment_pr:
    runs-on: ubuntu-latest
    name: Job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment on PR
        uses: ./
        with:
          message: 'When your PR is succefully compiled, you will find the artifacts to test on [GitHub Actions](https://github.com/hyperion-project/hyperion.ng/actions/runs/${GITHUB_RUN_ID}).'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
