name: Hyperion CI Build
on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:

##########################
###### RPM workflow ######
##########################

  rpm_build:
    name: RPM Build GitHub Releases
    uses: ./.github/workflows/dnf.yml
    secrets:
      APT_GPG: ${{ secrets.APT_GPG }}
      APT_USER: ${{ secrets.APT_USER }}
      APT_PASSWORD: ${{ secrets.APT_PASSWORD }}
      APT_DRAFT: ${{ secrets.APT_DRAFT }}
