name: Hyperion CI Build
on:
  push:
    branches-ignore:
      - 'gh-pages'
      - 'docker-ci'
    tags:
      - '*'

jobs:

######################
###### Windows #######
######################

  windows:
    name: Windows
    runs-on: windows-latest
    env:
      VCINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC'
      QT_VERSION: 5.15.0
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Powershell test
        shell: pwsh
        run: conda install -c conda-forge libjpeg-turbo

      - name: Cache Qt
        uses: actions/cache@v2
        id: cache-qt-windows
        with:
          path: ${{ runner.workspace }}/Qt
          key: ${{ runner.os }}-Qt.${{ env.QT_VERSION }}

