name: Hyperion CI Build
on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:

###################
###### macOS ######
###################

  macOS:
    name: macOS
    runs-on: macos-latest
    env:
      VCPKG_PACKAGES: qt5-base libusb python3
      VCPKG_DEFAULT_TRIPLET: arm64-osx
      VCPKG_DEFAULT_HOST_TRIPLET: x64-osx
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Bootstrap vcpkg
        run: |
          brew update & brew install cmake automake ninja
          $VCPKG_INSTALLATION_ROOT/vcpkg integrate install

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: $VCPKG_INSTALLATION_ROOT/installed
          key: vcpkg-installed-arm64-osx

      - name: Remove outdated packages from cache
        run: vcpkg remove --outdated --recurse

      - name: Build dependencies
        run: vcpkg install --clean-after-build --recurse ${{ env.VCPKG_PACKAGES }}

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: vcpkg-logs
          path: $VCPKG_INSTALLATION_ROOT/buildtrees/**/*.log

      - name: Set up gcc/clang problem matcher
        uses: ammaraskar/gcc-problem-matcher@master

      # - name: Configure
      #   run: |
      #     mkdir build && cd build
      #     cmake -B build \
      #       -DPLATFORM=osx \
      #       -DCMAKE_BUILD_TYPE=Release \
      #       -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
      #       -DCMAKE_OSX_ARCHITECTURES=arm64 \
      #       -DCMAKE_SYSTEM_PROCESSOR=arm64 \
      #       -DCMAKE_SYSTEM_NAME=Darwin \
      #       -DVCPKG_TARGET_TRIPLET=arm64-osx-release \
      #       -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake \
      #       -DCMAKE_INSTALL_PREFIX:PATH=/usr/local ../

      # - name: Build
      #   run: |
      #     cmake --build build -j $(sysctl -n hw.logicalcpu) package

      # Upload artifacts (only on tagged commit)
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: build/Hyperion-*
