name: Hyperion CI Build
on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:

##########################
###### YUM workflow ######
##########################

  yum_build:
    name: YUM Build GitHub Releases
    uses: ./.github/workflows/yum.yml
    secrets:
      YUM_GPG: ${{ secrets.YUM_GPG }}
      YUM_USER: ${{ secrets.YUM_USER }}
      YUM_PASSWORD: ${{ secrets.YUM_PASSWORD }}
      YUM_DRAFT: ${{ secrets.YUM_DRAFT }}
