name: Hyperion CI Build
on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:

###################
###### macOS ######
###################

  macOS:
    name: macOS
    runs-on: macos-11
    env:
      VCPKG_DEFAULT_TRIPLET: arm64-osx-min1100
      VCPKG_DEFAULT_HOST_TRIPLET: x64-osx-min1012
      PYTHON_VERSION: "3.11.4"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup/Restore Homebrew cache
        uses: actions/cache@v3
        id: cache-homebrew
        with:
          path: "$(brew --cache)"
          key: brew-cache-x64-osx

      - name: Install x64 build dependencies (Homebrew)
        if: ${{ steps.cache-homebrew.output.cache-hit != 'true' }}
        run: |
          brew update && brew install cmake automake ninja
          /bin/bash -c "sudo xcode-select --switch /Applications/Xcode_12.4.app/Contents/Developer"
          xcrun --show-sdk-version

      - name: Bootstrap vcpkg
        run: |
          $VCPKG_INSTALLATION_ROOT/vcpkg integrate install

      - name: Setup/Restore vcpkg cache
        uses: actions/cache@v3
        id: cache-vcpkg
        with:
          path: $VCPKG_INSTALLATION_ROOT/installed
          key: vcpkg-cache-arm64-osx

      - name: Install arm64 build dependencies (vcpkg)
        if: ${{ steps.cache-vcpkg.output.cache-hit != 'true' }}
        run: vcpkg remove --outdated --recurse && vcpkg install --clean-after-build --recurse qt5-base libusb

      - name: Upload vcpkg build logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          path: "/usr/local/share/vcpkg/buildtrees/**/*.log"

      - name: Setup/Restore Python download
        uses: actions/cache@v3
        id: cache-python-pkg
        with:
          path: ~/python.pkg
          key: python-download-osx-${{ env.PYTHON_VERSION }}

      - name: Download Python
        if: steps.cache-python-pkg.outputs.cache-hit != 'true'
        run: curl https://www.python.org/ftp/python/${PYTHON_VERSION}/python-${PYTHON_VERSION}-macos11.pkg -o ~/python.pkg

      - name: Install Python
        run: |
          sudo installer -pkg ~/python.pkg -target /
          unlink /usr/local/bin/python
          ln -s /usr/local/bin/python3 /usr/local/bin/python

      # - name: Configure
      #   run: |
      #     mkdir build && cd build
      #     cmake -B build \
      #       -DPLATFORM=osx \
      #       -DCMAKE_BUILD_TYPE=Release \
      #       -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
      #       -DCMAKE_OSX_ARCHITECTURES=arm64 \
      #       -DCMAKE_SYSTEM_PROCESSOR=arm64 \
      #       -DCMAKE_SYSTEM_NAME=Darwin \
      #       -DVCPKG_TARGET_TRIPLET=arm64-osx-release \
      #       -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake \
      #       -DCMAKE_INSTALL_PREFIX:PATH=/usr/local ../

      # - name: Build
      #   run: |
      #     cmake --build build -j $(sysctl -n hw.logicalcpu) package

      # Upload artifacts (only on tagged commit)
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     path: build/Hyperion-*
