name: Hyperion CI Build
on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:

#####################
###### Windows ######
#####################

  windows:
    name: Windows
    runs-on: windows-2022
    env:
      VCINSTALLDIR: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC'
      QT_VERSION: 5.15.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{env.QT_VERSION}}
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          cache: 'true'
          cache-key-prefix: 'cache-qt-windows'

      - name: Cache choco packages
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}\choco_cache
          key: ${{ hashFiles('.github/workflows/push-master.yml') }}
          restore-keys: |
            ${{ runner.os }}-chocolatey-cache-choco-packages-
            ${{ runner.os }}-chocolatey-
            ${{ runner.os }}

      - name: Install OpenSSL, DirectX SDK
        shell: powershell
        run: |
          Write-Output "::group::Install OpenSSL, DirectX SDK"
          choco install --no-progress -y --cache-location=${{github.workspace}}\choco_cache --forceX64 openssl directx-sdk
          Write-Output "::endgroup::"

      - name: Install libjpeg-turbo
        run: |
          Invoke-WebRequest https://netcologne.dl.sourceforge.net/project/libjpeg-turbo/2.0.6/libjpeg-turbo-2.0.6-vc64.exe -OutFile libjpeg-turbo.exe -UserAgent NativeHost
          .\libjpeg-turbo /S

      - name: Set up x64 build architecture environment
        shell: cmd
        run: call "${{env.VCINSTALLDIR}}\Auxiliary\Build\vcvars64.bat"

      # Build packages
      - name: Build packages
        env:
          PLATFORM: windows
        shell: bash
        run: ./.ci/ci_build.sh

      # Upload artifacts (only on tagged commit)
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: build/Hyperion-*
          retention-days: 1
