name: GitHub Qt5/6 Builds

on:
  # Reusable from push_pull.yml
  workflow_call:
    inputs:
      qt_version:
        type: string
        description: Build with this Qt version
        default: '5'
        required: false

env:
  ghcr: hyperion-project

jobs:
  macOS:
    name: 🍏 macOS test
    runs-on: macos-latest
    steps:
      - name: ⬇ Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 🔧 Prepare
        shell: bash
        run: |
          brew untap --force homebrew/core homebrew/cask
          brew update || true
          brew install qt${{ inputs.qt_version }} || true

      - name: 👷 Build
        shell: bash
        run: ./.github/scripts/build.sh
        env:
          PLATFORM: osx
