name: GitHub Qt5/6 Builds

on:
  # Reusable from push_pull.yml
  workflow_call:
    inputs:
      qt_version:
        type: string
        description: Build with this Qt version
        default: '5'
        required: false
      event_name:
        type: string
        description: The event name
        default: ''
        required: false
      pull_request_number:
        type: string
        description: The corresponding PR number
        default: ''
        required: false
      publish:
        type: boolean
        description: Package publishing
        default: false
        required: false

env:
  ghcr: hyperion-project

jobs:

######################
###### macOS #########
######################

  macOS:
    name: 🍏 macOS x64
    runs-on: macos-latest
    steps:
      - name: ⬇ Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 🔧 Prepare
        shell: bash
        run: |
          echo '::group::Append PR number to version (PR  only)'
            if [[ "${{ inputs.event_name }}" = "pull_request" ]]; then
              tr -d '\n' < .version > temp && mv temp .version
              echo -n "+PR${{ inputs.pull_request_number }}" >> .version
            fi
          echo '::endgroup::'

          echo '::group::Update/Install dependencies'
            brew untap --force homebrew/core homebrew/cask
            brew update || true
            brew install qt${{ inputs.qt_version }} vulkan-headers || true
          echo '::endgroup::'

      - name: 👷 Build
        shell: bash
        run: ./.github/scripts/build.sh
        env:
          PLATFORM: osx

      - name: 📦 Upload
        if: ${{ inputs.publish || inputs.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.event_name == 'pull_request' && env.NAME || 'artifact' }}
          path: 'build/Hyperion-*'
        env:
          NAME: ${{ inputs.qt_version == '6' && 'macOS_x64_qt6' || 'macOS_x64' }}

