name: RPM Packages build for DNF Repository

on:
  # Reusable from nightly.yml and push_pull.yml
  workflow_call:
    inputs:
      head_sha:
        type: string
        description: The branch, tag or SHA to checkout
        default: "master"
        required: false
      nightly:
        type: boolean
        description: Nightly build
        default: false
        required: false
      upload:
        type: boolean
        description: Upload Artifacts
        default: false
        required: false

env:
  ghcr: hyperion-project

jobs:
  build:
    name: 🐧 ${{ matrix.os.distribution }} ${{ matrix.os.version }} (${{ matrix.architecture[0] }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [
          { distribution: Fedora, version: 37 },
          { distribution: Fedora, version: 38 },
          { distribution: Fedora, version: 39 },
          { distribution: Fedora, version: 40 }
        ]
        architecture: [
          [ amd64, linux/amd64 ]
        ]

    steps:
      - name: ⬇ Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.head_sha || github.event.client_payload.head_sha }}
          submodules: recursive

      - name: 🔧 Prepare
        run: |
          echo '::group::Checking the version number'
            if [[ "${{ inputs.nightly }}" = true ]]; then
              echo VERSION=$(tr -d '\n' < .version)+nightly$(date '+%Y%m%d')$(git rev-parse --short HEAD | sed s/-/_/g) >> $GITHUB_ENV
            else
              echo VERSION=$(tr -d '\n' < .version | sed s/-/_/g) >> $GITHUB_ENV
            fi
          echo '::endgroup::'

      - name: 🛠️ Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: 👷 Build
        shell: bash
        run: |
          echo '::group::Building Hyperion'
            mkdir -p "${GITHUB_WORKSPACE}/deploy"
            docker run --rm --platform=${{ matrix.architecture[1] }} \
              -w "/root" \
              -v "${GITHUB_WORKSPACE}/deploy:/deploy" \
              -v "${GITHUB_WORKSPACE}:/root/hyperion.ng:rw" \
              ghcr.io/${{ env.ghcr }}/$(echo '${{ matrix.os.distribution }}' | tr '[:upper:]' '[:lower:]'):${{ matrix.os.version }}-qt6 \
              /bin/bash -c "tar -czf rpmbuild/SOURCES/hyperion.ng.tar.gz hyperion.ng/ && \
              cp -f hyperion.ng/rpmbuild/hyperion.spec.in rpmbuild/SPECS/hyperion.spec && \
              rpmdev-bumpspec --comment='${{ env.COMMIT_MESSAGE }}' --userstring='${{ env.ACTOR }}' rpmbuild/SPECS/hyperion.spec && \
              rpmbuild -ba --define '_version ${{ env.VERSION }}' rpmbuild/SPECS/hyperion.spec --clean && \
              cp -fv rpmbuild/RPMS/$(uname -m)/hyperion* /deploy"
          echo '::endgroup::'
        env:
          ACTOR: "Hyperion Project <admin@hyperion-project.org>"
          COMMIT_MESSAGE: ${{ github.event.commits[0].message }}

      - name: 📦 Upload
        if: ${{ inputs.upload }}
        uses: actions/upload-artifact@v3
        with:
          path: deploy
          retention-days: 1
